#!/bin/sh
#
# Awesome
#
# Sets up awesomewm
#
mkdir -p ~/.config/awesome
ln -s ~/.dotfiles/awesome/rc.lua ~/.config/awesome/rc.lua

## Copy over the custom theme file
#if [$(uname -s) == "Linux"]
#then
  mkdir -p /usr/share/awesome/themes/custom/
  sudo ln -s ~/.dotfiles/awesome/theme.lua /usr/share/awesome/themes/custom/theme.lua
#fi


