#!/bin/sh
#
# bootstrap installs things.

set -e

if [$(uname -s) == "Darwin"] 
then
  # * Install homebrew packages
  brew bundle
fi


# * Install Prezto for ZSH
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Create links to *.symlink files in ~/
rake install

# Install Base16 Shell
git clone https://github.com/tinted-theming/base16-shell.git \
  $HOME/.config/base16-shell

# HACK: install aws-mfa. Replace 3.9 with whatever macos installs
/usr/bin/pip3 install aws-mfa
sudo ln -s ~/Library/Python/3.9/bin/aws-mfa /usr/local/bin/aws-mfa

# NEXT STEPS:
#
# 1. Open Alacritty
# 2. Run vim (should auto-install vim-plugged)
# 3. Import private GPG key
# 4. Change default web browser to Firefox Developer Edition
# 5. Remove keyboard shortcut for Ctrl+up and Ctrl+down (mission control - we want tmux pane resize
# instead)
# 6. Change keyboard shortcut Caps Lock to Escape (vim)
# 7. Install ruby (e.g. rbenv install 3.2.2) then rbenv rehash
# 8. Install bundler (e.g. gem install bundler)
# 9. Add secrets: bundle config enterprise.contribsys.com KEY:VAL
# 10. Add long term AWS creds in ~/.aws/credentials

