#!/bin/sh
#
# bootstrap installs things.

# Install homebrew + brew file, supporting install from ~/.brewfile
set -e

if [$(uname -s) == "Darwin"] 
then
  curl -fsSL https://raw.github.com/rcmdnk/homebrew-file/install/install.sh |sh
fi

# * Install homebrew packages
brew file install

# * Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# * Install Postgres.app
# * Install latest ruby
# * gem-defaults
# * clone Plug.vim
# * clone tpm (tmux plugin manager)

# Create links to *.symlink files in ~/
rake install

# Install Bas16 Shell
git clone git@github.com:chriskempson/base16-shell.git ~/.config/base16-shell

# Install custom zsh theme
ln -s ~/.dotfiles/zsh/agnoster-hale.zsh-theme ~/.oh-my-zsh/themes/agnoster-hale.zsh-theme
